{{ if .Values.global.ingress }}
{{ if .Values.global.ingress.https }}
{{ if .Values.global.ingress.letsencryptEmail }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  serviceName: traefik-ingress-lb
  replicas: 0
  selector:
    matchLabels:
      app: traefik-ingress-lb
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
        k8s-app: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v2.5.2
          name: traefik-ingress-lb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/acme"
              name: "acme"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 8080
              name: admin
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetesCRD
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email="{{ .Values.global.ingress.letsencryptEmail }}"
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: acme
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
      email = "{{ .Values.global.ingress.letsencryptEmail }}"
      storage = "/acme/acme.json"
      entryPoint = "https"
      onHostRule = true
      acmeLogging = true
      [acme.httpChallenge]
        entryPoint = "http"
---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
  annotations:
  {{- range $k, $v := .Values.global.ingress.loadbalancerAnnotations }}
    {{ $k }}: {{ $v }}
  {{- end }}
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: LoadBalancer
{{ end }}
{{ end }}
{{ end }}
