apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  creationTimestamp: null
  name: airy-core
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/ws.communication`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-websocket"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/conversations`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-communication"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/messages`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-communication"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/metadata.upsert`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-communication"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/media.uploadFile`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "media-resolver"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/login`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/logout`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/oauth`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/client.config`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/users.getProfile`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.list`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.info`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.update`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.chatplugin`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/webhooks`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/tags`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/templates`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "api-admin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.facebook`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-facebook-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.instagram`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-facebook-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.viber`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-viber-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.google`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-google-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/channels.twilio`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-twilio-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/facebook`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-facebook-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/google`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-google-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/twilio`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-twilio-connector"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/ws.chatplugin`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-chatplugin"
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.global.kubernetes.host }}`) && PathPrefix(`/chatplugin`)
    middlewares: []
    priority: 0
    services:
    - kind: Service
      name: "sources-chatplugin"
      port: 80
  tls:
    certResolver: myresolver
