api:
  admin:
    component: api-admin
    image: api/admin
    mandatory: true
    enabled: true
    resources:
      requests:
        cpu: "100m"  
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"
