component: sources-facebook
mandatory: false
enabled: true
connector:
  image: sources/facebook-connector
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
eventsRouter:
  image: sources/facebook-events-router
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
