component: sources-chat-plugin
mandatory: false
enabled: true
backend:
  image: sources/chat-plugin
  resources:
    requests:
      cpu: "50m"  
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
frontend:
  image: frontend/chat-plugin
  resources:
    requests:
      cpu: "50m"  
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
