apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  - port: 9121
    targetPort: 9121
    name: exporter
  selector:
    app: redis-cluster
