alertmanager:
  ingress:
    enabled: true
    hosts: []
    paths: ['/alertmanager']
grafana:
  defaultDashboardsEnabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    hosts: []
    path: /grafana
prometheus:
  ingress:
    enabled: true
    hosts: []
    paths: ['/alertmanager']
    additionalScrapeConfigs:
    - job_name: redis_exporter
      static_configs:
      - targets: ['redis-cluster:9121']
