name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...

      - name: Lint
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run //:check

      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...

      - name: Deploy component library
        if: ${{github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix-components-deploy'}}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          SOURCE_DIR: 'bazel-bin/frontend/showcase/bundle'
