name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get -y install openjdk-11-jdk openjdk-11-jre

      - name: Check Software versions
        run: |
          java -version
          sudo dpkg -l | grep -i jdk || true
          sudo dpkg -l | grep -i jre || true
          jar --version || true
          ls -lah $(which python) || true

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Enable CI settings
        run: |
          echo "$GCS_SA_KEY" > key.json
          cat <<EOF >>.bazelrc
            common --config=ci
            build:ci --google_credentials=key.json
          EOF
        env:
          GCS_SA_KEY: ${{secrets.GCS_SA_KEY}}

      - name: Push images
        if: startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/test-ci')
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u airydevci --password-stdin
          bazel run //backend/sources/twilio/connector:ljupco-test-ci
